classdef fused_SHEncoding < deep.DifferentiableFunction
    methods
        function foo = fused_SHEncoding()
            output_num = 1; % important!!!
            foo@deep.DifferentiableFunction(...
                            output_num,...
                            SaveInputsForBackward = true,...
                            SaveOutputsForBackward = false,...
                            NumMemoryValues = 0);
        end
        
        %% forward function
        function out_feature = forward(~,...
                                  dirs,...
                                  feature_dims)
   
            out_feature = fullyfused_shEncoder( ...
                'forward',...
                dirs,...
                feature_dims...
            );
        end
        
        %% backward function
        function [dl_ddirs,...
                  dl_dfeature_dims] = backward(~,...
                                                dl_dout, ...
                                                computeGradients, ...
                                                dirs,...
                                                feature_dims)
            dl_dfeature_dims = [];
            dl_ddirs = fullyfused_shEncoder(...
                'backward',...
                dirs,...
                dl_dout,...
                feature_dims...
            );
        end
    end
end


function check_nan(x,name)
if sum(isnan(x),'all') > 0
    error(name + "has nan!");
end
end